<?php

namespace AppBundle\Repository;

/**
 * VisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get DAU (daily active users) from database
     *
     * @param \DateTime $dateFrom
     * @param \DateTime $dateTo
     *
     * @return array
     *
     */
    public function getDau($dateFrom, $dateTo)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT count(v.userId) FROM AppBundle:Visit v
                WHERE v.visitedAt BETWEEN :date_from AND :date_to
                GROUP BY v.userId
            ')
            ->setParameter('date_from', $dateFrom)
            ->setParameter('date_to', $dateTo);

        return $query->getResult();
    }
}
